User/urls.py
from django.urls import path
from. import views

app_name = 'User'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('accounts/', include('allauth.urls')),
    
]

Products/models.py
from django.db import models
from django.db.models.fields import CharField
import datetime
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    weight = models.PositiveBigIntegerField(null=True)
    price = models.PositiveBigIntegerField(null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now(),blank=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True) 


    def __str__(self):
        return self.name
    

User/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=3000)    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) 
    title = models.CharField(max_length=200)
    
    
    def __str__(self):
        return self.title

User/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = '__all__'

Products/views.py
from django.shortcuts import render

# Create your views here.

User/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import PostCreateForm
from .models import Post

def home(request):
    template = 'blog/home.html'
    posts = Post.objects.all().order_by('-updated')
    context = {
                'posts': posts,
            }
    return render(request,template,context)

@login_required(login_url='/accounts/login/') 
def create(request):
    template = 'blog/create.html'
    form = PostCreateForm()
    

    if request.method == 'POST':
        post_create = PostCreateForm(request.POST)
        if post_create.is_valid():
            
            post_create.save()
            messages.success(request, f'Your Post is created successfully !')
            return redirect('User:home')   
    context = {
        'form':form,
    }
    return render(request,template,context)

User/templates/blog/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container col-md-5">
    
    <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-outline-success" type="submit">Submit >></button>
    </form>
    
    
</div>
{% endblock content %}

User/templates/blog/home.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <br>
    <h1>HELLO {{request.user}} !</h1>
    <br>

    <a href="{% url 'User:create' %}" class="btn btn-success" >Create Post</a>
    <br><br>
    {% for post in posts  %}
      {{post.user}}
      {{post.text}}
      {{post.title}}
      <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h3 class="card-title">{{post.title}}</h3>
            <br>
            <h6 class="card-subtitle">Created by -> {{post.user}}</h6>
            <p class="card-text">{{post.text}}</p>
            <p class="card-text"><b>Created at -></b>{{post.created}}</p>
            <p class="card-text"><b>updated at -></b>{{post.updated}}</p>
          </div>
        </div>
    {% endfor %}
  </div>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <title>User </title>
</head>

<body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'User:home' %}">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'User:home' %}">Home</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>


    {% block content %}

    {% endblock content %}
    
</body>

</html>